version: 2
workflows:
  version: 2
  commit:
    jobs:
      - test
  nightly:
    triggers:
      - schedule:
          cron: "50 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:14.17.0-browsers
      - image: vimagick/dante
        command: bash -c "eval 'useradd user && echo user:password | chpasswd && sockd -f /etc/dante/sockd.conf -p /tmp/sockd.pid'"
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pnpm-lock.yaml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install --prefix=$HOME/.local --global pnpm
      - run: pnpm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "pnpm-lock.yaml" }}

      # run tests!
      - run: pnpm run ci:test-unit
      - run: pnpm run ci:test-func
      - run: pnpm run ci:style-check
      - run: pnpm run ci:lint
