name: test

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      proxy-for-test:
        image: vimagick/dante
        ports:
          - 1080:1080

    steps:
      - run: firefox --version
      - run: |
          container_id=$(docker ps -q)
          docker exec $container_id -- bash -c "eval 'useradd user && echo user:password | chpasswd && sockd -f /etc/dante/sockd.conf -p /tmp/sockd.pid'"
          docker restart $container_id
      - run: node --version && npm --version
      - run: npm install -g pnpm
      - uses: actions/checkout@v2
      - run: pnpm install
      - run: pnpm run ci:test-unit
      - run: pnpm run ci:test-func
      - run: pnpm run ci:style-check
      - run: pnpm run ci:lint
